name: Generate Pacman Graph

on:
  schedule:
    - cron: "0 */12 * * *" # cada 12 horas
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate pacman contributions graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Move graph to output folder
        run: |
          mkdir -p output
          mv dist/pacman-contribution-graph.svg output/

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add output/pacman-contribution-graph.svg
          git commit -m "Update pacman contributions graph" || echo "No changes to commit"
          git push
